#!/usr/bin/env bash
# Regenerate `install-manifest` from the live GitHub releases.
#
# Run this from a maintainer's machine after releasing any component in the install
# set. It needs `gh` authenticated; `install.sh` itself needs neither gh nor a token,
# because it reads the generated file over plain HTTPS.
#
# The digests are read from the releases API `digest` field, which GitHub computes over
# the stored asset. They are never taken from agentic-host's `.host-software`, whose
# hashes describe a locally built artifact rather than the published bytes
# (plan/0071, plan/0065 lines 121-132).
#
# Regenerating and finding no diff is how the manifest is verified: it proves every
# recorded hash still matches what the release serves.

set -euo pipefail

OWNER=connollydavid
HERE=$(cd "$(dirname "$0")" && pwd)
OUT=$HERE/install-manifest

# The install set. Held at the two components publishing a complete platform matrix,
# which are also the two the README asks an adopter for. Widening it means the added
# component must publish all six assets first.
COMPONENTS="host-lifecycle host-lint"

# Every platform the install claims. A component missing any one of these cannot join
# the set, because the install is all-or-nothing.
PLATFORMS="darwin-amd64 darwin-arm64 linux-amd64 linux-arm64 windows-amd64 windows-arm64"

command -v gh >/dev/null || { echo "make-install-manifest: needs gh on PATH" >&2; exit 1; }

# The template revision this manifest is keyed to. `host` install is also the upgrade
# route, so an adopter installing at a revision gets the binaries that revision expects.
template=$HERE/../../../host-template
[ -e "$template/.git" ] || { echo "make-install-manifest: cannot read the host-template revision" >&2; exit 1; }
revision=$(git -C "$template" rev-parse --short HEAD)

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
    echo "# host install manifest. Generated by make-install-manifest.sh; do not hand-edit."
    echo "# Regenerate after any release in the install set, then commit the diff."
    echo "#"
    echo "#   template-revision <sha>"
    echo "#   binary <name> <version> <platform> <url> <sha256>"
    echo ""
    echo "template-revision $revision"
    echo ""
} > "$tmp"

for component in $COMPONENTS; do
    # One call per component: the first line is the tag, the rest are the assets.
    release=$(gh release view -R "$OWNER/$component" --json tagName,assets \
        --jq '.tagName, (.assets[] | "\(.name) \(.url) \(.digest)")')
    tag=$(printf '%s\n' "$release" | head -1)
    version=${tag#v}

    for platform in $PLATFORMS; do
        case $platform in
            windows-*) asset="$component-$platform.exe" ;;
            *)         asset="$component-$platform" ;;
        esac

        # Match by exact asset name. This is what keeps a pack out by construction:
        # host-lint publishes `host-lint-ffmpeg-<platform>` beside the core binary, and
        # that is not this name.
        found=$(printf '%s\n' "$release" | awk -v want="$asset" \
            '$1 == want { sub(/^sha256:/, "", $3); print $2, $3; exit }')

        if [ -z "$found" ]; then
            echo "make-install-manifest: $component $tag publishes no $asset" >&2
            echo "  the install is all-or-nothing, so a component missing a platform cannot be in the set" >&2
            exit 1
        fi

        echo "binary $component $version $platform $found" >> "$tmp"
    done
done

mv "$tmp" "$OUT"
trap - EXIT
echo "wrote $OUT (template revision $revision)"
